name = "cloudflare-docker-proxy"
compatibility_date = "2024-10-09"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "wzxmt.site"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "wzxmt.site"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "tylhjsevjg.wzxmt.site", custom_domain = true },
  { pattern = "tiwpengobr.wzxmt.site", custom_domain = true },
  { pattern = "ztwuicjnkq.wzxmt.site", custom_domain = true },
  { pattern = "bdyfvhmrph.wzxmt.site", custom_domain = true },
  { pattern = "rwayianyvf.wzxmt.site", custom_domain = true },
  { pattern = "rnydvvgapq.wzxmt.site", custom_domain = true },
  { pattern = "wyvczirkvu.wzxmt.site", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[observability]
enabled = true
