name = "cloudflare-docker-proxy"
compatibility_date = "2026-04-15"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "wzxt.asia"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "wzxt.asia"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "tylhjsevjg.wzxt.asia", custom_domain = true },
  { pattern = "tiwpengobr.wzxt.asia", custom_domain = true },
  { pattern = "ztwuicjnkq.wzxt.asia", custom_domain = true },
  { pattern = "bdyfvhmrph.wzxt.asia", custom_domain = true },
  { pattern = "rwayianyvf.wzxt.asia", custom_domain = true },
  { pattern = "rnydvvgapq.wzxt.asia", custom_domain = true },
  { pattern = "wyvczirkvu.wzxt.asia", custom_domain = true },
  { pattern = "ecrwyvczir.wzxt.asia", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

#[env.staging]
#name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.wzxt.asia", custom_domain = true }

#[env.staging.vars]
#MODE = "staging"
#TARGET_UPSTREAM = ""
#test
